Moves VM details to Job model allowing differing images/flavors/etc
Duke-GCB/bespin-workflows pull request #120
Opened 2017-12-13 17:13 UTC by dleehr

- Adds VMSettings and CloudSettings models, populated via migrations
- Refactors Job and JobQuestionnaire to reference these settings so that a Job object contains all of the `vm_settings` from the lando server (image name, openstack project, volume mounts, cwl command)
- Refactors JobFactory to incorporate these new settings, copying from the questionnaire to the job
- Updates `loadworkflow` command to expect the name of a VMSettings instead of a VM project name
- Adds nested fields to AdminJobSerializer, allowing admin clients to get VM and cloud settings in the job payload 

Tested migrations by loading current dev and prod databases into local postgres then migrating.

The migrations will only fill out the bare minimum fields for VMSettings and CloudSettings. These must be further populated from what's currently in the lando server configs, and should be addressed at deploy time by a fixture.

Some issues in the migrations were not discovered until trying to migrate on postgres. Created  #119.

Fixes #115

2017-12-13 17:19 UTC, dleehr commented
I'll be testing this out on dev today, so more commits may come.

2017-12-14 18:22 UTC, johnbradley requested changes
Requesting some minor tweaks.
Overall LGTM.

2017-12-14 18:22 UTC, johnbradley commented on data/models.py
> +
For consistency with VMSettings do you want to add something like:
```
class Meta:
    verbose_name_plural = "Cloud Settings Collections"
```

Right now the admin interface shows this as `Cloud settingss`.

2017-12-14 18:22 UTC, johnbradley commented on data/models.py
> +
Extra blank line (PEP8).

2017-12-14 18:22 UTC, johnbradley commented on data/models.py
> +                                  help_text='VM Flavor to use when creating VM instances for this questionnaire')
Shouldn't this help_text end with `for this job` instead of `for this questionnaire`?

2017-12-14 18:35 UTC, johnbradley approved these changes

2017-12-14 18:37 UTC, merged