Adds questionnaire endpoints for end user job editing
Duke-GCB/bespin-workflows pull request #16
Opened 2017-01-13 21:30 UTC by johnbradley

Adds endpoints:

- `/api/job-questions/` - contains all questions that could be answered for a job
- `/api/job-questionnaires/` - questionnaire is a list of questions required for a particular job
- `/api/job-answers/` - answers to a question - if tied to a questionnaire they are read only - otherwise editable by the user who created it
- `/api/job-string-answers/` - string value associated with an answer
- `/api/job-dds-file-answers/` - DukeDS file info associated with an answer
- `/api/job-answer-sets/` - group of user answers and the questionnaire they apply to

Fixes #14

2017-01-17 20:41 UTC, dleehr requested changes
I was able to run the migrations and

1. add a number of questions
2. add a questionnaire

Adding answers failed because of the above mentioned issue, so this should be addressed.

Also, if a system answer is to be a file path (e.g. a reference genome that will be on the VM), would that be a string answer? What about an integer (like number of threads?)

2017-01-17 20:41 UTC, dleehr commented on data/models.py
> +        return '{} question:{} - value:{}'.format(self.id, self.answer.question.name, self.value)
By setting `primary_key=True`, the `id` field is not added, so this raises an exception when I try to create a JobStringAnswer through the Admin UI. `self.pk`should work.

> AttributeError at /admin/data/jobstringanswer/add/
> 'JobStringAnswer' object has no attribute 'id'

https://docs.djangoproject.com/en/1.10/ref/models/fields/#primary-key

2017-01-17 20:41 UTC, dleehr commented on data/models.py
> +        return '{} question:{} - file_id:{}'.format(self.id, self.answer.question.name, self.file_id)
Same as above. setting a custom `primary_key` field means that `self.id` doesn't exist.

2017-01-17 21:10 UTC, johnbradley commented
> Also, if a system answer is to be a file path (e.g. a reference genome that will be on the VM), would that be a string answer? 

Yes. My thought was the question would be data_type `File` and the answer would be data type `string`

>  What about an integer (like number of threads?)

For right now, yes. My thought was the question would be data_type `int` and the answer would be data type `string` So we convert the string to an integer before building CWL input json. I can add __job-integer-answers__ if it would help.

There has been no code written(yet) that converts the questionnaire to a CWL input JSON blob.

2017-01-17 21:21 UTC, dleehr commented
That's fine. We can work with strings, just wanted to make sure it would be accepted. 

I'm testing this locally with Ember. As it exists now, Ember will require special-casing for the endpoints that don't have an `id` field (the ones where primary_key is overridden). Is there a big benefit to breaking this convention on the Django side? I gather that we'd add a field in our table, but it bucks the convention and requires special-casing on the client.

2017-01-17 21:31 UTC, johnbradley commented
>I'm testing this locally with Ember. As it exists now, Ember will require special-casing for the endpoints that don't have an id field (the ones where primary_key is overridden). Is there a big benefit to breaking this convention on the Django side? I gather that we'd add a field in our table, but it bucks the convention and requires special-casing on the client.

I was just following the Django example for OneToOneField (https://docs.djangoproject.com/en/1.10/topics/db/examples/one_to_one/).
I can remove the primary_key property and see what happens.

2017-01-17 21:34 UTC, dleehr commented
I can try that here, was just curious of the reasoning. It makes sense on the django side, since the field would be unique anyways and is required. I suppose we could even just add an `id` field to the serializer, as a copy of the answer field, but I'll investigate what Ember needs.

2017-01-18 13:55 UTC, johnbradley commented
I removed the `primary_key=True` property from those two tables. Everything seems to still work fine. I'm fine with this change if it helps the front-end and back-end fit together better.

2017-01-25 19:35 UTC, johnbradley commented
@dleehr Do you have further changes requested that I am missing?

2017-01-25 19:36 UTC, dleehr approved these changes

2017-01-25 19:40 UTC, merged